<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class OuvrageSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('t_ouvrage')->insert([
            ['ouvrage_id' => 1, 'titre' => 'Le Petit Prince', 'extrait' => 'Un conte poétique...', 'resume' => 'L’histoire d’un garçon qui quitte sa planète pour explorer l’univers. Il rencontre des personnages symboliques comme un roi, un vaniteux et un géographe, chacun représentant des aspects de la société adulte. Sur Terre, il découvre la valeur de l’amitié et de l’amour grâce à un renard et une rose, apprenant que l’essentiel est invisible aux yeux.', 'annee' => 1943, 'image' => 'petitprince.jpg', 'nbPages' => 96, 'utilisateur_fk' => 2, 'categorie_fk' => 1, 'editeur_fk' => 1, 'auteur_fk' => 1],
            ['ouvrage_id' => 2, 'titre' => '1984', 'extrait' => 'Un roman dystopique...', 'resume' => 'Winston Smith vit dans une société totalitaire contrôlée par Big Brother. Employé au ministère de la Vérité, il falsifie les archives pour servir la propagande. Il se rebelle secrètement, tombe amoureux de Julia, et découvre l’horreur d’un monde où la surveillance détruit la liberté et la vérité.', 'annee' => 1949, 'image' => '1984.jpg', 'nbPages' => 328, 'utilisateur_fk' => 2, 'categorie_fk' => 2, 'editeur_fk' => 2, 'auteur_fk' => 2],
            ['ouvrage_id' => 3, 'titre' => 'Le Seigneur des Anneaux', 'extrait' => 'Une épopée fantastique...', 'resume' => 'Frodo, un hobbit, hérite de l’Anneau unique, un puissant artefact maléfique. Avec ses amis, il entreprend une quête pour détruire l’Anneau au mont Destin, affrontant des forces obscures et des épreuves qui testent leur courage et leur amitié.', 'annee' => 1954, 'image' => 'Le_Seigneur_des_Anneaux.jpg', 'nbPages' => 1216, 'utilisateur_fk' => 3, 'categorie_fk' => 3, 'editeur_fk' => 3, 'auteur_fk' => 3],
            ['ouvrage_id' => 4, 'titre' => 'À la recherche du temps perdu', 'extrait' => 'Un roman de la mémoire...', 'resume' => 'Marcel Proust explore ses souvenirs et ses émotions, racontant des histoires sur l’amour, la jalousie et le passage du temps. Ce voyage introspectif met en lumière la quête de sens et la réconciliation avec le passé.', 'annee' => 1913, 'image' => 'temps.jpg', 'nbPages' => 1400, 'utilisateur_fk' => 3, 'categorie_fk' => 4, 'editeur_fk' => 4, 'auteur_fk' => 4],
            ['ouvrage_id' => 5, 'titre' => 'Le Comte de Monte-Cristo', 'extrait' => 'Un roman d’aventure...', 'resume' => 'Edmond Dantès, victime d’un complot, est emprisonné injustement. Après s’évader et découvrir un trésor, il change d’identité et orchestre une vengeance implacable contre ses ennemis, tout en luttant avec ses propres conflits intérieurs.', 'annee' => 1844, 'image' => 'comte.jpg', 'nbPages' => 1240, 'utilisateur_fk' => 2, 'categorie_fk' => 5, 'editeur_fk' => 5, 'auteur_fk' => 5],
            ['ouvrage_id' => 6, 'titre' => 'Les Misérables', 'extrait' => 'Une épopée de la misère...', 'resume' => 'Jean Valjean, ancien forçat en quête de rédemption, croise les chemins de Cosette, une orpheline qu’il élève comme sa fille, et de Javert, un inspecteur déterminé à le capturer. À travers des luttes sociales et personnelles, l’histoire explore la justice, la misère et la foi en l’humanité.', 'annee' => 1862, 'image' => 'miserables.jpg', 'nbPages' => 1464, 'utilisateur_fk' => 1, 'categorie_fk' => 1, 'editeur_fk' => 2, 'auteur_fk' => 6],
            ['ouvrage_id' => 7, 'titre' => 'L’Alchimiste', 'extrait' => 'Un conte philosophique...', 'resume' => 'Santiago, un jeune berger andalou, part à la recherche d’un trésor caché près des pyramides d’Égypte. Sur son chemin, il rencontre divers mentors, comme un alchimiste, qui lui apprennent à suivre ses rêves et à comprendre le langage universel de l’âme.', 'annee' => 1988, 'image' => 'alchimiste.jpg', 'nbPages' => 208, 'utilisateur_fk' => 1, 'categorie_fk' => 2, 'editeur_fk' => 3, 'auteur_fk' => 7],
            ['ouvrage_id' => 8, 'titre' => 'Le Vieil Homme et la Mer', 'extrait' => 'Une fable sur la persévérance...', 'resume' => 'Santiago, un vieux pêcheur cubain, part seul en mer pour capturer un énorme marlin. Après un combat épuisant et courageux, il triomphe, mais doit affronter la perte de sa prise face aux requins, illustrant le thème de la persévérance face à l’échec.', 'annee' => 1952, 'image' => 'Le_Vieil_Homme_et_la_Mer.jpg', 'nbPages' => 127, 'utilisateur_fk' => 1, 'categorie_fk' => 3, 'editeur_fk' => 4, 'auteur_fk' => 8],
            ['ouvrage_id' => 9, 'titre' => 'La Peste', 'extrait' => 'Une épidémie qui bouleverse...', 'resume' => 'Dans une ville algérienne frappée par une épidémie de peste, les habitants luttent pour leur survie. À travers les récits des personnages, le roman explore la solidarité, l’absurdité de la condition humaine et la résilience face à la souffrance collective.', 'annee' => 1947, 'image' => 'peste.jpg', 'nbPages' => 288, 'utilisateur_fk' => 1, 'categorie_fk' => 4, 'editeur_fk' => 5, 'auteur_fk' => 9],
            ['ouvrage_id' => 10, 'titre' => 'Les Fleurs du mal', 'extrait' => 'Un recueil de poèmes...', 'resume' => 'Ce recueil de poèmes de Charles Baudelaire mêle beauté et angoisse, abordant des thèmes comme l’amour, la mort, le spleen et la quête d’un idéal inaccessible. Il reflète la tension entre la noirceur de l’existence et l’aspiration à l’éternité.', 'annee' => 1857, 'image' => 'fleurs_du_mal.jpg', 'nbPages' => 140, 'utilisateur_fk' => 3, 'categorie_fk' => 5, 'editeur_fk' => 1, 'auteur_fk' => 10],
            ['ouvrage_id' => 11, 'titre' => 'Le Da Vinci Code', 'extrait' => 'Un thriller mystérieux...', 'resume' => 'Robert Langdon, un professeur de symbologie, est entraîné dans une quête haletante après le meurtre du conservateur du Louvre. Avec l’aide de Sophie Neveu, il décrypte une série d’énigmes liées à des œuvres d’art et des secrets religieux, révélant une conspiration sur les origines du christianisme.', 'annee' => 2003, 'image' => 'davinci.jpg', 'nbPages' => 489, 'utilisateur_fk' => 2, 'categorie_fk' => 1, 'editeur_fk' => 2, 'auteur_fk' => 11],
            ['ouvrage_id' => 12, 'titre' => 'Orgueil et Préjugés', 'extrait' => 'Une romance classique...', 'resume' => 'Elizabeth Bennet, l’une des cinq filles d’une famille anglaise modeste, affronte les préjugés sociaux et les malentendus avec Mr Darcy, un homme riche et réservé. Leur relation évolue au fil de réflexions sur l’amour, l’orgueil et les attentes de la société.', 'annee' => 1813, 'image' => 'orgueil.jpg', 'nbPages' => 432, 'utilisateur_fk' => 2, 'categorie_fk' => 2, 'editeur_fk' => 3, 'auteur_fk' => 12],
            ['ouvrage_id' => 13, 'titre' => 'Le Journal d’Anne Frank', 'extrait' => 'Un témoignage de guerre...', 'resume' => 'Dans son journal intime, Anne Frank raconte sa vie quotidienne alors qu’elle se cache avec sa famille dans un grenier à Amsterdam pendant la Seconde Guerre mondiale. Ses écrits offrent un témoignage poignant sur la peur, l’espoir et le passage à l’âge adulte.', 'annee' => 1947, 'image' => 'journal_anne_frank.jpg', 'nbPages' => 283, 'utilisateur_fk' => 1, 'categorie_fk' => 3, 'editeur_fk' => 4, 'auteur_fk' => 13],
            ['ouvrage_id' => 14, 'titre' => 'Le Horla', 'extrait' => 'Une nouvelle fantastique...', 'resume' => 'Un homme est hanté par une présence invisible qui semble contrôler son esprit et ses actions. À travers son journal, il décrit sa descente dans la folie et sa lutte contre cet être surnaturel, incarnant les peurs de l’inconnu et du trouble mental.', 'annee' => 1887, 'image' => 'le_horla.jpg', 'nbPages' => 55, 'utilisateur_fk' => 1, 'categorie_fk' => 4, 'editeur_fk' => 5, 'auteur_fk' => 14],
            ['ouvrage_id' => 15, 'titre' => 'L’Étranger', 'extrait' => 'Un roman philosophique...', 'resume' => 'Meursault, un jeune homme indifférent, vit en marge de la société algérienne. Après la mort de sa mère, il commet un meurtre absurde sous l’effet de la chaleur et est jugé plus pour son manque d’émotions que pour son acte, révélant l’absurdité de l’existence.', 'annee' => 1942, 'image' => 'etranger.jpg', 'nbPages' => 123, 'utilisateur_fk' => 1, 'categorie_fk' => 5, 'editeur_fk' => 1, 'auteur_fk' => 9],
            ['ouvrage_id' => 16, 'titre' => 'Crime et Châtiment', 'extrait' => 'Un roman psychologique...', 'resume' => 'Rodion Raskolnikov, un étudiant pauvre, commet un meurtre sous prétexte de justice sociale, mais il est hanté par la culpabilité et l’angoisse. Son cheminement moral le pousse à chercher la rédemption, explorant les thèmes du crime, de la punition et du salut.', 'annee' => 1866, 'image' => 'crime_et_chatiment.jpg', 'nbPages' => 430, 'utilisateur_fk' => 1, 'categorie_fk' => 1, 'editeur_fk' => 2, 'auteur_fk' => 19],
            ['ouvrage_id' => 17, 'titre' => 'Le Petit Nicolas', 'extrait' => 'Une série de récits humoristiques...', 'resume' => 'À travers une série de récits humoristiques, Nicolas raconte ses aventures quotidiennes avec ses amis, ses parents et ses enseignants. Ces histoires pleines de malice et d’innocence capturent la vie et les préoccupations d’un enfant dans la France des années 1950.', 'annee' => 1959, 'image' => 'petit_nicolas.jpg', 'nbPages' => 192, 'utilisateur_fk' => 3, 'categorie_fk' => 2, 'editeur_fk' => 3, 'auteur_fk' => 17],
            ['ouvrage_id' => 18, 'titre' => 'Dracula', 'extrait' => 'Un roman gothique...', 'resume' => 'Le jeune notaire Jonathan Harker se rend en Transylvanie pour rencontrer le comte Dracula, sans savoir qu’il est un vampire. Alors que Dracula voyage en Angleterre, une bataille s’engage entre lui et un groupe d’amis déterminés à stopper ses plans diaboliques.', 'annee' => 1897, 'image' => 'dracula.jpg', 'nbPages' => 418, 'utilisateur_fk' => 3, 'categorie_fk' => 3, 'editeur_fk' => 4, 'auteur_fk' => 18],
            ['ouvrage_id' => 19, 'titre' => 'Le Parfum', 'extrait' => 'Un roman sur le pouvoir des odeurs...', 'resume' => 'Jean-Baptiste Grenouille, né avec un sens olfactif exceptionnel, devient obsédé par la création du parfum parfait. Dans sa quête, il commet des meurtres pour capturer les essences de jeunes femmes, illustrant les ténèbres de son génie et la puissance des odeurs.', 'annee' => 1985, 'image' => 'parfum.jpg', 'nbPages' => 263, 'utilisateur_fk' => 2, 'categorie_fk' => 4, 'editeur_fk' => 5, 'auteur_fk' => 16],
            ['ouvrage_id' => 20, 'titre' => 'Mémoires d’une Geisha', 'extrait' => 'Une histoire fascinante...', 'resume' => 'Chiyo, une jeune fille japonaise vendue à une maison de geishas, raconte son parcours pour devenir une geisha renommée. À travers ses luttes et ses réussites, elle dévoile les traditions, les sacrifices et les émotions derrière ce monde fascinant mais impitoyable.', 'annee' => 1997, 'image' => 'memoires_geisha.jpg', 'nbPages' => 434, 'utilisateur_fk' => 1, 'categorie_fk' => 5, 'editeur_fk' => 1, 'auteur_fk' => 15],

        ]);
    }
}
